# To override values here make a file named 'Gruntconfig--custom.yml' - it will be git ignored

jsDir: source/js/
jsDest: public/js/
sassDir: source/sass/
sassDest: public/css/
imagesDir: source/images/
bowerDir: bower_components/

# This is the destination of the CMS theme these source files will be ported to
themeDest: ../theme/

# Doppelganger Static HTML wrapper
doppelgangerDir: ../doppelganger/
doppelgangerTemp: doppelganger/